### ISSUE TITLE
Error when trying to download CSV file from AARTFAAC Images

### ISSUE THREAD

**Issue by ycendes** [transientskp/banana#110] opened 2015-11-06 16:50 UTC
I was trying to download the csv file for the latest batch of AARTFAAC images so I could get the measured RMS values: http://banana.transientskp.org/master/vlo_SB003cendes/images/?format=csv&dataset=TRAP%20dataset

But got an error.  I think it might be looking for some information in the files that isn't there, but it's not clear to me just what that is. (I should note one can download the running catalog CSV files just fine.) It appears to happen for all the other AARTFAAC files though.

Just in case the above link doesn't work, here's the particular data set where this happens: http://banana.transientskp.org/master/vlo_SB003cendes/dataset/8/

**Comment by gijzelaerr** [comment] 2015-11-13 09:12
looks like a duplicate of https://github.com/transientskp/banana/issues/109 ?

**Comment by AntoniaR** [comment] 2015-11-13 09:13
Not quite, it's the image page rather than the new sources page - but basically the same I think.
It's not AARTFAAC specific, as it is also with some LOFAR fits images.

**Closed** 2015-11-20 12:29 UTC
Labels: bug
